### ISSUE TITLE
HipTest-publisher must check for the correct ruby version before installing

### ISSUE THREAD

**Issue by mm3599** [hiptest/hiptest-publisher#34] opened 2016-07-20 19:36 UTC
I've had a problem where I installed Ruby on Ubuntu 14.04 using apt-get and the debian repo only contains 1.9.1.

Then I run the hip-test install gem install hiptest-publisher and it installs.
When I try to run it, it complains that I don't have the correct version of Ruby (must be 2.3).

esadmin@hiptest:~$ hiptest-publisher --config-file hiptest-publisher.conf --test-run-id 7
Error: you are using ruby 1.9.3.
hiptest-publisher requires Ruby version >= 2.0.0.
esadmin@hiptest:~$ ruby --version
ruby 2.2.5p319 (2016-04-26 revision 54774) [x86_64-linux-gnu]

I've spent about 2-3 hours working through how to fix this.

So, please update gem install hiptest-publisher to check for the correct Ruby version and not install if it is not found.

Thanks,
Mark

**Comment by cbliard** [comment] 2016-10-20 11:32
A gem can not prevent its installation. It's only once installed that the ruby version can be known by the gem and that it can display an error indicating that the ruby version does not match.

That's why we can not prevent installation of the hiptest-publisher gem if the ruby version does not match.

In your case, it looks like the problem is different: it looks like two different ruby versions are installed and they are conflicting each other. The ruby executable show 2.2.5, but the gems think that 1.9.3 is installed. My recommendation is to remove any ruby packages currently installed, especially the ruby packages proposed by your distribution, and then to install ruby using [rvm](http://rvm.io/).

**Comment by cbliard** [comment] 2017-12-04 17:07
Closing as there is no more activity

**Closed by cbliard** 2017-12-04 17:07 UTC
